export const greekLetters: Record<string, string> = {
  "\\alpha": "α", "\\beta": "β", "\\gamma": "γ",
  "\\delta": "δ", "\\epsilon": "ε", "\\varepsilon": "ε",
  "\\zeta": "ζ", "\\eta": "η", "\\theta": "θ",
  "\\vartheta": "ϑ", "\\iota": "ι", "\\kappa": "κ",
  "\\lambda": "λ", "\\mu": "μ", "\\nu": "ν",
  "\\xi": "ξ", "\\pi": "π", "\\varpi": "ϖ",
  "\\rho": "ρ", "\\varrho": "ϱ", "\\sigma": "σ",
  "\\varsigma": "ς", "\\tau": "τ", "\\upsilon": "υ",
  "\\phi": "φ", "\\varphi": "φ", "\\chi": "χ",
  "\\psi": "ψ", "\\omega": "ω",
  "\\Gamma": "Γ", "\\Delta": "Δ", "\\Theta": "Θ",
  "\\Lambda": "Λ", "\\Xi": "Ξ", "\\Pi": "Π",
  "\\Sigma": "Σ", "\\Upsilon": "Υ", "\\Phi": "Φ",
  "\\Psi": "Ψ", "\\Omega": "Ω",
};

export const symbols: Record<string, { val: string; tag: "mo" | "mi" }> = {
  "\\pm": { val: "±", tag: "mo" },
  "\\mp": { val: "∓", tag: "mo" },
  "\\times": { val: "×", tag: "mo" },
  "\\div": { val: "÷", tag: "mo" },
  "\\cdot": { val: "·", tag: "mo" },
  "\\cdots": { val: "⋯", tag: "mo" },
  "\\ldots": { val: "…", tag: "mo" },
  "\\vdots": { val: "⋮", tag: "mo" },
  "\\ddots": { val: "⋱", tag: "mo" },
  "\\neq": { val: "≠", tag: "mo" },
  "\\ne": { val: "≠", tag: "mo" },
  "\\approx": { val: "≈", tag: "mo" },
  "\\le": { val: "≤", tag: "mo" },
  "\\leq": { val: "≤", tag: "mo" },
  "\\ge": { val: "≥", tag: "mo" },
  "\\geq": { val: "≥", tag: "mo" },
  "\\ll": { val: "≪", tag: "mo" },
  "\\gg": { val: "≫", tag: "mo" },
  "\\equiv": { val: "≡", tag: "mo" },
  "\\sim": { val: "~", tag: "mo" },
  "\\simeq": { val: "≃", tag: "mo" },
  "\\cong": { val: "≅", tag: "mo" },
  "\\propto": { val: "∝", tag: "mo" },
  "\\infty": { val: "∞", tag: "mi" },
  "\\partial": { val: "∂", tag: "mi" },
  "\\nabla": { val: "∇", tag: "mi" },
  "\\sum": { val: "∑", tag: "mo" },
  "\\int": { val: "∫", tag: "mo" },
  "\\iint": { val: "∬", tag: "mo" },
  "\\iiint": { val: "∭", tag: "mo" },
  "\\oint": { val: "∮", tag: "mo" },
  "\\prod": { val: "∏", tag: "mo" },
  "\\sin": { val: "sin", tag: "mi" },
  "\\cos": { val: "cos", tag: "mi" },
  "\\tan": { val: "tan", tag: "mi" },
  "\\csc": { val: "csc", tag: "mi" },
  "\\sec": { val: "sec", tag: "mi" },
  "\\cot": { val: "cot", tag: "mi" },
  "\\arcsin": { val: "arcsin", tag: "mi" },
  "\\arccos": { val: "arccos", tag: "mi" },
  "\\arctan": { val: "arctan", tag: "mi" },
  "\\sinh": { val: "sinh", tag: "mi" },
  "\\cosh": { val: "cosh", tag: "mi" },
  "\\tanh": { val: "tanh", tag: "mi" },
  "\\coth": { val: "coth", tag: "mi" },
  "\\log": { val: "log", tag: "mi" },
  "\\ln": { val: "ln", tag: "mi" },
  "\\exp": { val: "exp", tag: "mi" },
  "\\lim": { val: "lim", tag: "mo" },
  "\\max": { val: "max", tag: "mi" },
  "\\min": { val: "min", tag: "mi" },
  "\\sup": { val: "sup", tag: "mi" },
  "\\inf": { val: "inf", tag: "mi" },
  "\\det": { val: "det", tag: "mi" },
  "\\gcd": { val: "gcd", tag: "mi" },
  "\\deg": { val: "deg", tag: "mi" },
  "\\dim": { val: "dim", tag: "mi" },
  "\\ker": { val: "ker", tag: "mi" },
  "\\Pr": { val: "Pr", tag: "mi" },
  "\\arg": { val: "arg", tag: "mi" },
  "\\mod": { val: "mod", tag: "mo" },
  "\\forall": { val: "∀", tag: "mo" },
  "\\exists": { val: "∃", tag: "mo" },
  "\\nexists": { val: "∄", tag: "mo" },
  "\\neg": { val: "¬", tag: "mo" },
  "\\lnot": { val: "¬", tag: "mo" },
  "\\land": { val: "∧", tag: "mo" },
  "\\wedge": { val: "∧", tag: "mo" },
  "\\lor": { val: "∨", tag: "mo" },
  "\\vee": { val: "∨", tag: "mo" },
  "\\oplus": { val: "⊕", tag: "mo" },
  "\\otimes": { val: "⊗", tag: "mo" },
  "\\vdash": { val: "⊢", tag: "mo" },
  "\\models": { val: "⊨", tag: "mo" },
  "\\because": { val: "∵", tag: "mo" },
  "\\therefore": { val: "∴", tag: "mo" },
  "\\rightarrow": { val: "→", tag: "mo" },
  "\\leftarrow": { val: "←", tag: "mo" },
  "\\leftrightarrow": { val: "↔", tag: "mo" },
  "\\Rightarrow": { val: "⇒", tag: "mo" },
  "\\Leftarrow": { val: "⇐", tag: "mo" },
  "\\Leftrightarrow": { val: "⇔", tag: "mo" },
  "\\longrightarrow": { val: "⟶", tag: "mo" },
  "\\longleftarrow": { val: "⟵", tag: "mo" },
  "\\Longrightarrow": { val: "⟹", tag: "mo" },
  "\\Longleftrightarrow": { val: "⟺", tag: "mo" },
  "\\to": { val: "→", tag: "mo" },
  "\\gets": { val: "←", tag: "mo" },
  "\\mapsto": { val: "↦", tag: "mo" },
  "\\hookrightarrow": { val: "↪", tag: "mo" },
  "\\uparrow": { val: "↑", tag: "mo" },
  "\\downarrow": { val: "↓", tag: "mo" },
  "\\nearrow": { val: "↗", tag: "mo" },
  "\\searrow": { val: "↘", tag: "mo" },
  "\\rightleftharpoons": { val: "⇌", tag: "mo" },
  "\\leftharpoonup": { val: "↼", tag: "mo" },
  "\\rightharpoonup": { val: "⇀", tag: "mo" },
  "\\in": { val: "∈", tag: "mo" },
  "\\notin": { val: "∉", tag: "mo" },
  "\\ni": { val: "∋", tag: "mo" },
  "\\subset": { val: "⊂", tag: "mo" },
  "\\supset": { val: "⊃", tag: "mo" },
  "\\subseteq": { val: "⊆", tag: "mo" },
  "\\supseteq": { val: "⊇", tag: "mo" },
  "\\nsubseteq": { val: "⊄", tag: "mo" },
  "\\cap": { val: "∩", tag: "mo" },
  "\\cup": { val: "∪", tag: "mo" },
  "\\emptyset": { val: "∅", tag: "mi" },
  "\\varnothing": { val: "∅", tag: "mi" },
  "\\setminus": { val: "∖", tag: "mo" },
  "\\mid": { val: "|", tag: "mo" },
  "\\nmid": { val: "∤", tag: "mo" },
  "\\angle": { val: "∠", tag: "mo" },
  "\\perp": { val: "⊥", tag: "mo" },
  "\\parallel": { val: "∥", tag: "mo" },
  "\\triangle": { val: "△", tag: "mi" },
  "\\square": { val: "□", tag: "mi" },
  "\\circ": { val: "∘", tag: "mo" },
  "\\hbar": { val: "ℏ", tag: "mi" },
  "\\ell": { val: "ℓ", tag: "mi" },
  "\\dagger": { val: "†", tag: "mo" },
  "\\ddagger": { val: "‡", tag: "mo" },
  "\\star": { val: "⋆", tag: "mo" },
  "\\bullet": { val: "•", tag: "mo" },
  "\\prime": { val: "′", tag: "mo" },
  "\\aleph": { val: "ℵ", tag: "mi" },
  "\\Re": { val: "ℜ", tag: "mi" },
  "\\Im": { val: "ℑ", tag: "mi" },
  "\\iff": { val: "⇔", tag: "mo" },
  "\\implies": { val: "⇒", tag: "mo" },
};

export const delimiterMap: Record<string, string> = {
  "\\lfloor": "&#x230A;",
  "\\rfloor": "&#x230B;",
  "\\lceil": "&#x2308;",
  "\\rceil": "&#x2309;",
  "\\langle": "&#x27E8;",
  "\\rangle": "&#x27E9;",
  ".": "",
};

export const matrixDelimiters: Record<string, [string, string]> = {
  pmatrix: ["(", ")"],
  bmatrix: ["[", "]"],
  Bmatrix: ["{", "}"],
  vmatrix: ["|", "|"],
  Vmatrix: ["\u2016", "\u2016"],
};

export const decoratorMap: Record<string, { tag: "mover" | "munder"; char: string; stretchy?: boolean }> = {
  "\\vec": { tag: "mover", char: "&#x2192;", stretchy: false },
  "\\hat": { tag: "mover", char: "^", stretchy: false },
  "\\overline": { tag: "mover", char: "&#x00AF;", stretchy: true },
  "\\underline": { tag: "munder", char: "_", stretchy: true },
  "\\bar": { tag: "mover", char: "&#x00AF;" },
  "\\tilde": { tag: "mover", char: "~" },
  "\\dot": { tag: "mover", char: "." },
  "\\ddot": { tag: "mover", char: ".." },
  "\\overrightarrow": { tag: "mover", char: "&#x2192;", stretchy: true },
  "\\underbrace": { tag: "munder", char: "&#x23DF;", stretchy: true },
  "\\overbrace": { tag: "mover", char: "&#x23DE;", stretchy: true },
};

export const mathVariantMap: Record<string, string> = {
  "\\mathcal": "script",
  "\\mathbf": "bold",
  "\\mathbb": "double-struck",
};
